spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springJpa
    username: gian
    password: gian
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true